### ISSUE TITLE
[Events] Live Now indicator shows/hides randomly

### ISSUE THREAD

**Issue by asleepingpanda** [christfellowshipchurch/web-app#184]
When a Live Stream is active, the LIVE NOW indicator will show/hide on irregular intervals.

Some examples of this bug as reported by users:

"The live stream just became active, but it took 5-10 minutes before my screen showed the Live Stream Feed"
"The live stream did not show until I changed devices or opened up a Private Browser"
"Yesterday's Live Stream shows as Active today, still, even though it's no longer active"

We believe this to be a combination of an issue with Caching and Fetch Policy on the Live Provider/consumer, although we have yet to nail down the exact cause for it.

This issue is becoming a higher risk for Content Integrity as we're looking to add Chat to our Live Streams and get rid of ChOP

**Comment by rkdavidson** [comment]
Closing as we are reimplementing all this logic/behavior for web-v2.
